
services:
  url-shortener:
    build: .
    container_name: url-shortener-container
    ports:
      - "8080:8080"
    volumes:
      # Maps the 'db_data' folder on your laptop to the '/app/data' folder inside Docker
      - ./db_data:/app/data
    restart: always

  # ðŸ“Š METRICS COLLECTOR
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  # ðŸ“ˆ VISUALIZATION DASHBOARD
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password
    depends_on:
      - prometheus